"""cascade deletes for projects

Revision ID: ba3e20360d7f
Revises: 500ebcf5ff58
Create Date: 2025-11-24 20:02:31.837555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba3e20360d7f"
down_revision: Union[str, Sequence[str], None] = "500ebcf5ff58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("bug_project_id_fkey"), "bug", type_="foreignkey")
    op.create_foreign_key(
        None, "bug", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bug", type_="foreignkey")
    op.create_foreign_key(
        op.f("bug_project_id_fkey"), "bug", "project", ["project_id"], ["id"]
    )
    # ### end Alembic commands ###
