"""Add bug_history table 2

Revision ID: cf4220e9e5c3
Revises: a83219334290
Create Date: 2025-11-27 21:04:49.690220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4220e9e5c3'
down_revision: Union[str, Sequence[str], None] = 'a83219334290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bug.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bug_history_bug_id', 'bug_history', ['bug_id'], unique=False)
    op.create_index('idx_bug_history_changed_at', 'bug_history', ['changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bug_history_changed_at', table_name='bug_history')
    op.drop_index('idx_bug_history_bug_id', table_name='bug_history')
    op.drop_table('bug_history')
    # ### end Alembic commands ###
